server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  application:
    name: openBar-server
  datasource:
    url: jdbc:h2:mem:database
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console